general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }

[window]
decorations = "None"
dynamic_padding = true
blur = true

[terminal]
shell = { program = "/home/linuxbrew/.linuxbrew/bin/tmux", args = ["new-session", "-A", "-s", "main"] }
