creation_rules:
  - path_regex: .*
    age:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBdCjQKKktRc6DXvVQnTo9xEMm5ZZj+EGfewg1mwTbaM aly@petalburg
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAx92dtg9xdm8D444KxgkRlfoGDUwkFIIf2Lv6ZuoG/b aly@fortree
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEza8l5QxWOrSedLJVMc9xXxKnJhOREKQMf61uBgEYk0 aly@eterna
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQW3A2E57TuybFXybSk/KUC/rlUR7gICQ8oBAKHwwVK aly@pacifidlog
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3YdXgLFwvyVAzj3CpqCf079SEhX3EzNEu2rFR3Bbyb aly@jubilife
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPxGj4y75Q7fZt59MkSwhqqg6ARRRnNC3HSJPTHtR93Z aly@rustboro
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKxdI0Djvnue/AJznfd9iDpVrY/2OQFov0EwAhZ1tNf0 aly@sootopolis
